######################################################################
##
## Filename: top_tb.udo
## Created on: Wed Mar 31 20:33:09 Russia TZ 2 Standard Time 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
#Maximize window
wm state . zoom
#Show all as hex
radix -hexadecimal
#Supress Numeric Std package and Arith package warnings.#
#For VHDL designs we get some warnings due to unknown values on some signals at startup#
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0#
#We may also get some Arithmetic packeage warnings because of unknown values on#
#some of the signals that are used in an Arithmetic operation.#
#In order to suppress these warnings, we use following two commands#
set NumericStdNoWarnings 1
set StdArithNoWarnings 1

#
# Create work library
#
#vdel -all
vlib work

#
# Compile sources
#

#Compile files (excluding model parameter file)#

vcom -explicit  -93 "./src/utils/axis_reg.vhd"
vcom -explicit  -93 "./src/utils/axis_interconnect.vhd"
vcom -explicit  -93 "./src/utils/timer.vhd"
vcom -explicit  -93 "./src/utils/debouncer.vhd"

vcom -explicit  -93 "./src/ddr2/core/ddr2.vhd"
vcom -explicit  -93 "./src/ddr2/core/iodrp_controller.vhd"
vcom -explicit  -93 "./src/ddr2/core/iodrp_mcb_controller.vhd"
vcom -explicit  -93 "./src/ddr2/core/mcb_raw_wrapper.vhd"
vcom -explicit  -93 "./src/ddr2/core/mcb_soft_calibration_top.vhd"
vcom -explicit  -93 "./src/ddr2/core/mcb_soft_calibration.vhd"
vcom -explicit  -93 "./src/ddr2/core/memc3_infrastructure.vhd"
vcom -explicit  -93 "./src/ddr2/core/memc3_wrapper.vhd"

vcom -explicit  -93 "./src/ddr2/ddr2_interconnect.vhd"

vcom -explicit  -93 "./src/vid_mem/vid_mem_sprite.vhd"
vcom -explicit  -93 "./src/vid_mem/vid_mem_gen.vhd"

vcom -explicit  -93 "./src/tft/tft_fifo.vhd"
vcom -explicit  -93 "./src/tft/tft_ddr2_reader.vhd"
vcom -explicit  -93 "./src/tft/tft_video_timing_gen.vhd"
vcom -explicit  -93 "./src/tft/tft.vhd"
vcom -explicit  -93 "./src/tft/pwm.vhd"

vcom -explicit  -93 "./src/uart/uart_rx.vhd"
vcom -explicit  -93 "./src/uart/uart_tx.vhd"

vcom -explicit  -93 "./src/top/calc_ctrl.vhd"
vcom -explicit  -93 "./src/top/keypad_reader.vhd"
vcom -explicit  -93 "./src/top/seven_seg_ctrl.vhd"
vcom -explicit  -93 "./src/top/top.vhd"

vcom -explicit  -93 "./tbs/top/top_tb.vhd"

#Additional files
vlog $env(XILINX)/verilog/src/glbl.v

#Pass the parameters for memory model parameter file#
vlog  +incdir+. +define+x1Gb +define+sg25E +define+x16 "./tbs/top/ddr2_model_c3.v"

#Load the design. Use required libraries.#
vsim -t ps +notimingchecks -L unisim -L secureip work.top_tb glbl
#vsim -novopt -t ps +notimingchecks -L unisim -L secureip work.top_tb glbl

#add wave -position insertpoint sim:/top_tb/uut/vid_mem_gen_inst/*
#add wave -position insertpoint sim:/top_tb/uut/ddr2_interconnect_inst/*
do ./tbs/top/wave.do
#
# Run simulation for this time
#
run 1ms


#
# End
#
